In [1]:
import numpy as np

##### Linspace
A useful function for plotting mathematical functions is linspace. Linspace returns evenly spaced numbers over a specified interval.

In [2]:
 # numpy.linspace(start, stop, num = int value)
np.linspace(-5, 5, num = 9)     # num =9 means here that it will give you 9 digits in between -5, -5

array([-5.  , -3.75, -2.5 , -1.25,  0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [3]:
 #Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [4]:
# create any array of ones 
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# as you can see,the above array is in floats
# we can convert it into the int using astype(int)
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
# similarly we can create array of zeros
zero = np.zeros((3,2,2))   # the default data type is float.
zero

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
# creating array of random numbers integers
random = np.random.randint(10, size =(5, 3))
random

array([[4, 4, 9],
       [4, 6, 9],
       [7, 3, 1],
       [8, 3, 7],
       [9, 6, 0]], dtype=int32)

In [8]:
## random array of floats
float = np.random.random ((4, 3))
float

array([[0.70312039, 0.7345654 , 0.7121307 ],
       [0.06943933, 0.62032571, 0.43961602],
       [0.95481627, 0.14048005, 0.81095774],
       [0.61630662, 0.24981393, 0.9793797 ]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.
For consistency, you might want to keep the random numbers you generate similar throughout experiments.
To do this, you can use np.random.seed().

In [9]:
np.random.seed(0)
random = np.random.randint(10, size =(5, 3))
random

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)